### ISSUE TITLE
Missing code in OneHotEncoder section

### ISSUE THREAD

**Issue by larends** [learn-co-curriculum/dsc-sklearn-preprocessing-lab#1]
Towards the end, when we're using OneHotEncoder, the key shows

fireplace_qu_encoded_train = ohe.transform(fireplace_qu_train)

and then a printout of a numpy array (instead of the sparse matrix object that is returned). Run this way, there is an error in the next code block because of mismatched shapes.

I added .toarray() on the above code. (Not sure if that's the best way...)

**Comment by jessepisel** [comment]
I am unable to replicate this issue and am closing at this time.
